# Generated by Django 3.0.2 on 2020-03-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='phoneno',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
